services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 1s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASS}@database:5432/${DB_NAME}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFESPAN: ${JWT_LIFESPAN}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${BE_PORT}:80
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    ports:
      - ${FE_PORT}:80
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  database:
