[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--parser=html"] }
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--parser=css"] }
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser=json"] }
language-servers = ["vscode-json-language-server", "tailwindcss-ls"]

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser=typescript"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser=typescript"] }

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser=typescript"] }
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser=typescript"] }
language-servers = ["typescript-language-server", "tailwindcss-ls"]
